// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RetoHemoglobina.Infrastructure;

#nullable disable

namespace RetoHemoglobina.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251105164829_Inicial")]
    partial class Inicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RetoHemoglobina.Domain.Models.Alerta", b =>
                {
                    b.Property<byte>("Id")
                        .HasColumnType("tinyint");

                    b.Property<string>("TipoAlerta")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Alertas");

                    b.HasData(
                        new
                        {
                            Id = (byte)0,
                            TipoAlerta = "Sin alerta"
                        },
                        new
                        {
                            Id = (byte)1,
                            TipoAlerta = "Nivel bajo"
                        },
                        new
                        {
                            Id = (byte)2,
                            TipoAlerta = "Nivel alto"
                        });
                });

            modelBuilder.Entity("RetoHemoglobina.Domain.Models.Genero", b =>
                {
                    b.Property<byte>("Id")
                        .HasColumnType("tinyint");

                    b.Property<string>("TipoGenero")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Generos");

                    b.HasData(
                        new
                        {
                            Id = (byte)1,
                            TipoGenero = "Masculino"
                        },
                        new
                        {
                            Id = (byte)2,
                            TipoGenero = "Femenino"
                        });
                });

            modelBuilder.Entity("RetoHemoglobina.Domain.Models.Paciente", b =>
                {
                    b.Property<int>("Identificacion")
                        .HasColumnType("int");

                    b.Property<byte>("GeneroId")
                        .HasColumnType("tinyint");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Identificacion");

                    b.HasIndex("GeneroId");

                    b.ToTable("Paciente");

                    b.HasData(
                        new
                        {
                            Identificacion = 101,
                            GeneroId = (byte)1,
                            Nombre = "Carlos Mora"
                        },
                        new
                        {
                            Identificacion = 102,
                            GeneroId = (byte)2,
                            Nombre = "Laura Ríos"
                        });
                });

            modelBuilder.Entity("RetoHemoglobina.Domain.Models.ResultadoPaciente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<byte>("AlertaId")
                        .HasColumnType("tinyint");

                    b.Property<int>("Identificacion")
                        .HasColumnType("int");

                    b.Property<float>("Nivel")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("AlertaId");

                    b.HasIndex("Identificacion");

                    b.ToTable("Consultas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AlertaId = (byte)0,
                            Identificacion = 101,
                            Nivel = 14.5f
                        },
                        new
                        {
                            Id = 2,
                            AlertaId = (byte)1,
                            Identificacion = 102,
                            Nivel = 13.2f
                        });
                });

            modelBuilder.Entity("RetoHemoglobina.Domain.Models.Paciente", b =>
                {
                    b.HasOne("RetoHemoglobina.Domain.Models.Genero", "Genero")
                        .WithMany("Pacientes")
                        .HasForeignKey("GeneroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Genero");
                });

            modelBuilder.Entity("RetoHemoglobina.Domain.Models.ResultadoPaciente", b =>
                {
                    b.HasOne("RetoHemoglobina.Domain.Models.Alerta", "Alerta")
                        .WithMany("Resultados")
                        .HasForeignKey("AlertaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RetoHemoglobina.Domain.Models.Paciente", "Paciente")
                        .WithMany("Resultados")
                        .HasForeignKey("Identificacion")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Alerta");

                    b.Navigation("Paciente");
                });

            modelBuilder.Entity("RetoHemoglobina.Domain.Models.Alerta", b =>
                {
                    b.Navigation("Resultados");
                });

            modelBuilder.Entity("RetoHemoglobina.Domain.Models.Genero", b =>
                {
                    b.Navigation("Pacientes");
                });

            modelBuilder.Entity("RetoHemoglobina.Domain.Models.Paciente", b =>
                {
                    b.Navigation("Resultados");
                });
#pragma warning restore 612, 618
        }
    }
}
